[package]
name = "cadence"
version = "3.0.1"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dirs = "5"
rand = "0.8"

[dependencies.winapi]
version = "0.3"
features = [
    "winuser",
    "windef",
    "minwindef",
    "libloaderapi",
    "processthreadsapi",
    "profileapi",
    "timeapi",
    "synchapi",
    "winbase",
    "errhandlingapi",
    "wingdi",
    "commctrl",
    "sysinfoapi",
    "consoleapi",
    "processenv",
    "wincon",
]

[build-dependencies]
winres = "0.1"

[profile.release]
opt-level = 3
lto = true
